version: '3'
services:
  reservation:
    stdin_open: true
    tty: true
    build:
      context: .
    image: reservation
    container_name: reservation-ms
    volumes:
      - ./src:/opt/reservation
      - ./pom.xml:/opt/reservation/pom.xml
    ports:
          - "8484:8484"
          - "5434:5432"
